### ISSUE TITLE
Can't select No Category, No Version, e.t.c. in the QueryPanel

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-backlog-plugin#34]
#### Overview description

Can't select No Category, No Version, e.t.c. in the QueryPanel

#### Steps to reproduce

1. Open a new query panel 

#### Actual results

There are not No Category, No Version, No Milestone, Unassigned and No Resolution.

#### Expected results

We can select the above.

#### Version number of the plugin

0.3.2

#### Version information of NetBeans

8.0.2

Report from @DrSchranz

**Comment by junichi11** [comment]
![nb-backlog-issue34](https://cloud.githubusercontent.com/assets/738383/9560365/38063fc6-4e4a-11e5-9865-8648a10318f8.png)

**Comment by DrSchranz** [comment]
Hello,
I'm so happy with 0.3.3 and this fix, the plugin satisfies almost all my daily work with backlog, thanks! :) 
But seems that this fix needs a bit more, because saved queries doesn't apply this new options.  When doing a query from `QueryController.search()` it works, constructs `GetIssuesParams` from `QueryPanel` methods like `QueryPanel.getResolutions()` to obtain values from the selected item of the combo. But when `BacklogQuery.refresh()` it constructs a `GetIssuesParams` with his methods, that are doing a check with BacklogData's collections and discarding this new "-1" options.

I have created an Issue #36 to report this on the correct version, its correct?, or have to reuse this thread?

**Comment by junichi11** [comment]
Hi,

> But when BacklogQuery.refresh() it constructs a GetIssuesParams with his methods, that are doing a check with BacklogData's collections and discarding this new "-1" options.

Thanks for catching it :) I'll fix it.

> I have created an Issue #36 to report this on the correct version, its fine?, or have to reuse this thread?

Well... It's no problem because I've already released 0.3.3. If a new version is not released yet and there are missing something in my changes, you should just report them to the same issue before create a new issue. (You can reopen this issue because you are a collaborator).

Thanks!
